config/routes.rb
Rails.application.routes.draw do

  resources :cryptos
  devise_for :users
  get 'lookup' => "home#lookup"

  post "lookup" => 'home#lookup'

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user

  def symbol=(value)
    write_attribute(:symbol, value.upcase)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  before_action :api_call, only:[:index, :show]

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    @profit_loss = 0
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.cryptos.find_by(id:params[:id])
      redirect_to cryptos_path, notice: "Your not authorized to access that entry" if @correct.nil?
    end

    def api_call
      require 'net/http'
      require 'json'

      @url = 'https://api.coinmarketcap.com/v1/ticker/'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @coins = JSON.parse(@response)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :api_call, only:[:index, :lookup]

  def index
    @page_results = @coins.paginate(params[:page], 20)
  end

  def lookup
    @symbol = params[:sym]
    @symbol.upcase! if @symbol
    @symbol = "no coin entered" if @symbol == ''
  end

  private

    def api_call
      require 'net/http'
      require 'json'

      @coin_list= []
      @url = 'https://api.coinmarketcap.com/v1/ticker/'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @coins = JSON.parse(@response)
      @coins.map{|coin| @coin_list.push(coin['symbol'])}
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def pw_length password_length
    "#{password_length} characters minimum" if password_length
  end

  def active? path
    "active" if current_page? path
  end

  def number_with_del_prec value,precision
    number_with_delimiter(number_with_precision(value, precision: precision))
  end

end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper



  def coin_name
    if @coin_list.include?(@symbol)
      @coins.each do |coin|
        if @symbol.include?(coin['symbol'])
         return "#{coin['name']} (#{coin['symbol']})"
        end
      end
    else
      "Invalid"
    end
  end
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto, local: true) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :crypto_symbol, class:'form-control' %>
  </div>

  <div class="field hidden">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :crypto_user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, id: :crypto_cost_per, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, id: :crypto_amount_owned, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title">Editing Crypto</h2>
    </div>

    <div class="panel-body">
      <%= render 'form', crypto: @crypto %>
    </div>

    <div class="panel-footer ">
      <%= link_to 'Show', @crypto, class:'btn btn-primary' %>
      <%= link_to 'Back', cryptos_path, class:'btn btn-default'%>
    </div>

  </div>
</div>

app/views/cryptos/index.html.erb
<h1>Cryptos</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>1 HR Change</th>
      <th>24 HR Change</th>
      <th>7 DAY Change</th>
      <th>Total Current Value</th>
      <th>Profit/Loss</th>
      <th>Cost Paid per unit</th>
      <th>Amount owned</th>
      <th>Total Paid</th>

    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
      <% crypto.symbol = crypto.symbol.upcase if crypto %>
        <tr class="clickable-row" data-href="/cryptos/<%= crypto.id %>">
          <% @coins.each do |coin| %>
            <% if crypto.symbol.include?(coin['symbol']) %>
              <td><%= "#{coin['name']}(#{crypto.symbol})" %></td>
              <td>$<%= coin['price_usd'] %></td>
              <td><%= number_to_percentage(coin['percent_change_1h'], precision: 2) %></td>
              <td><%= number_to_percentage(coin['percent_change_24h'], precision: 2) %></td>
              <td><%= number_to_percentage(coin['percent_change_7d'], precision: 2) %></td>
              <td>$<%= coin['price_usd'].to_f * crypto.amount_owned %></td>
              <td>$<%= @profit_loss = ((coin['price_usd'].to_f * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)) %></td>
              <td>$<%= crypto.cost_per %></td>
              <td><%= crypto.amount_owned %></td>
              <td>$<%= crypto.amount_owned * crypto.cost_per %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <strong>Portfolio Profit/Loss:</strong> $<%= @profit_loss %>
</div>
<br />


<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-default" %>

app/views/cryptos/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title">New Crypto</h2>
    </div>

    <div class="panel-body">

      <%= render 'form', crypto: @crypto %>

    </div>
    <div class="panel-footer">
      <%= link_to 'Back', cryptos_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/cryptos/show.html.erb
<% @coins.each do |coin| %>
  <% if @crypto.symbol.include?(coin['symbol']) %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= coin['rank'] %>.  <%= coin['name'] %>(<%= coin['symbol'] %>)</h3>
      </div>

      <div class="panel-body">
        <div class="col-sm-4">
          <h4>Prices</h4>
          <p><b>Price <small>(USD)</small>:</b> $<%= coin['price_usd'] %> </p>
          <p><b>Price <small>(BTC)</small>:</b> <%= coin['price_btc'] %> </p>
          <p><b>24-HR Volume <small>(USD)</small>:</b> <%= number_to_currency(coin['24h_volume_usd']) %></p>
          <p><b>Market Cap <small>(USD)</small>:</b> <%= number_to_currency(coin['market_cap_usd']) %></p>
        </div>

        <div class="col-sm-4">
          <h4>Market Supply</h4>
          <p><b>Available:</b> <%= coin['available_supply'] %> <%= coin['symbol'] %></p>
          <p><b>Total:</b> <%= coin['total_supply'] %> <%= coin['symbol'] %></p>
          <p><b>Max:</b> <%= coin['max_supply'] %> <%= coin['symbol'] %></p>
        </div>

        <div class="col-sm-4">
          <h4>Market change</h4>
          <p><b>1 Hour:</b> <%= number_to_percentage(coin['percent_change_1h']) %></p>
          <p><b>24 hours:</b> <%= number_to_percentage(coin['percent_change_24h']) %></p>
          <p><b>7 Days:</b> <%= number_to_percentage(coin['percent_change_7d']) %></p>
        </div>
      </div>
    </div>

  <% end %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">My Portfolio</h3>
  </div>

  <div class="panel-body">
    <table class="table">
      <tr>
        <th>Total Current Value</th>
        <th>Profit/Loss</th>
        <th>Cost Paid per unit</th>
        <th>Amount owned</th>
        <th>Total Paid</th>
      </tr>

      <% @coins.each do |coin| %>
        <% if @crypto.symbol.include?(coin['symbol']) %>
          <tr>
            <td>$<%= coin['price_usd'].to_f * @crypto.amount_owned %></td>
            <td>$<%= @profit_loss = ((coin['price_usd'].to_f * @crypto.amount_owned) - (@crypto.cost_per * @crypto.amount_owned)) %></td>
            <td>$<%= @crypto.cost_per %></td>
            <td><%= @crypto.amount_owned %></td>
            <td>$<%= @crypto.amount_owned * @crypto.cost_per %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="panel-footer">
    <%= link_to 'Back', cryptos_path, class:'btn btn-default' %>
    <%= link_to 'Edit', edit_crypto_path(@crypto), class:'btn btn-warning' %>
    <%= link_to 'Delete', crypto_path(@crypto), method: :delete, class:'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/home/index.html.erb
<h1>top 100 Cryptocurrencies</h1>

<div class="digg_pagination">
  <%= will_paginate @page_results, class:'pagination' %>
</div>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Current Price <small>USD</small></th>
    <th>Market Cap <small>USD</small></th>
    <th>Available Supply</th>
    <th>Total Supply</th>
    <th>1 HR Change</th>
    <th>24 HR Change</th>
    <th>7 DAY Change</th>


  </tr>
  </thead>

  <tbody>
    <% @page_results.each do |coin| %>
      <tr>
        <td><%= coin['rank'] %>.</td>
        <td><%= "#{coin['name']} (#{coin['symbol']})" %></td>
        <td>$<%= number_with_delimiter(coin['price_usd']) %></td>
        <td>$<%= number_with_del_prec(coin['market_cap_usd'], 0) %></td>
        <td><%= "#{number_with_del_prec(coin['available_supply'], 0)} #{coin['symbol']}" %></td>
        <td><%= "#{number_with_del_prec(coin['total_supply'], 0)} #{coin['symbol']}" %></td>
        <td><%= number_to_percentage(coin['percent_change_1h'], precision: 2) %></td>
        <td><%= number_to_percentage(coin['percent_change_24h'], precision: 2) %></td>
        <td><%= number_to_percentage(coin['percent_change_7d'], precision: 2) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <%= will_paginate @page_results, class:'pagination' %>
</div>

app/views/home/lookup.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2 class="panel-title">Crypto Currency Lookup</h2>
    </div>

    <div class="panel-body form-inline">

      <%= form_tag lookup_path, method: "POST" do  %>
        <%= text_field_tag 'sym', nil, placeholder:'Enter Crypto Symbol', class:'form-control' %>
        <%= submit_tag "Find Crypto", class:'btn btn-primary full-width' %>
      <% end %>
    </div>

    <div class="panel-footer">
    </div>
  </div>
</div>

<% if @symbol %>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h2 class="panel-title"><%= coin_name %></h2>
      </div>

      <div class="panel-body">
        <% if @coin_list.include?(@symbol) %>
          <% @coins.each do |coin| %>
            <% if @symbol.include?(coin['symbol']) %>

              <div class="col-sm-4">
                <h4>Prices</h4>
                <p><b>Price <small>(USD)</small>:</b> $<%= coin['price_usd'] %> </p>
                <p><b>Price <small>(BTC)</small>:</b> <%= coin['price_btc'] %> </p>
                <p><b>24-HR Volume <small>(USD)</small>:</b> <%= number_to_currency(coin['24h_volume_usd']) %></p>
                <p><b>Market Cap <small>(USD)</small>:</b> <%= number_to_currency(coin['market_cap_usd']) %></p>
                <br />
              </div>

              <div class="col-sm-4">
                <h4>Market Supply</h4>
                <p><b>Available:</b> <%= number_with_del_prec(coin['available_supply'], 0) %> <%= coin['symbol'] %></p>
                <p><b>Total:</b> <%= number_with_del_prec(coin['total_supply'], 0) %> <%= coin['symbol'] %></p>
                <p><b>Max:</b> <%= number_with_del_prec(coin['max_supply'], 0) %> <%= coin['symbol'] %></p>
                <br />
              </div>

              <div class="col-sm-4">
                <h4>Market change</h4>
                <p><b>1 Hour:</b> <%= number_to_percentage(coin['percent_change_1h'],precision: 2) %></p>
                <p><b>24 hours:</b> <%= number_to_percentage(coin['percent_change_24h'],precision: 2) %></p>
                <p><b>7 Days:</b> <%= number_to_percentage(coin['percent_change_7d'],precision: 2) %></p>
              </div>
            <% end %>
          <% end %>
        <% else %>
          Please enter a valid coin
        <% end %>
      </div>
      <div class="panel-footer">
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Portfolio</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



  <%= render 'shared/navbar' %>


  <div class="container">
    <%= render 'shared/flash' %>
    <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |name,msg| %>
  <div class="alert alert-warning alert-dismissable">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Portfolio", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= active?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= active?(lookup_path) %>"><%= link_to "Lookup", lookup_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "My crypto wallet", cryptos_path %></li>
          <li><%= link_to "Add New", new_crypto_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> Profile <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign-out', destroy_user_session_path, method: 'DELETE' %></li>
            </ul>
          </li>
        <% else %>
          <li class="<%= active?(new_user_registration_path) %>"><%= link_to 'Sign-up', new_user_registration_path %></li>
          <li class="<%= active?(new_user_session_path) %>"><%= link_to 'Sign-in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>